POST http://localhost:1338/api/shows
Content-Type: application/json

{
    "name":"Severence",
    "description":"Weirdnessat his best",
    "streamingService":"Apple TV"
}


###

GET http://localhost:1338/api/shows

###
GET http://localhost:1338/api/status