POST http://localhost:1338/api/shows
Content-Type: application/json

{
    "name":"Twin Peaks: The Return",
    "description":"David Lynch at his best",
    "streamingService":"Amazon Prime"
}


###

GET http://localhost:1338/api/shows
