@Software.Api_HostAddress = http://localhost:1337

POST http://localhost:1337/vendors 
Content-Type: application/json

{
 "name": "",
  "url": "https://docker.com",
  "contact": {
    "name": "Satya",
    "email": "Satya@microsoft.com",
    "phone": "888 555-1212"
  }
}


### 

GET http://localhost:1337/vendors/9370712f-4a7e-4c37-b75a-1bbaf9e16c08

### 
GET http://localhost:1337/vendors 
