@Software.Api_HostAddress = http://localhost:1337

POST http://localhost:1337/vendors 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNhckBjb21wYW55LmNvbSIsInN1YiI6ImNhckBjb21wYW55LmNvbSIsImp0aSI6ImI1MTU0YjNiIiwicm9sZSI6IlNvZnR3YXJlQ2VudGVyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDoxMzM3IiwibmJmIjoxNzU1MTE2NTExLCJleHAiOjE3NjMwNjUzMTEsImlhdCI6MTc1NTExNjUxMiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9._dIwuXmGrPjfvC6--gkncPYpI0K1IzIQV5hivWheOIUMTc2MzA2NTEzNywiaWF0IjoxNzU1MTE2MzM5LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.abHDnuNksXYH7o4V7pYENUbclLUcREj2C-ATPeC-gvk

{
 "name": "Docker, Inc.",
  "url": "https://docker.com",
  "contact": {
    "name": "Satya",
    "email": "Satya@microsoft.com",
    "phone": "888 555-1212"
  }
}


### 

GET http://localhost:1337/vendors/9370712f-4a7e-4c37-b75a-1bbaf9e16c08

### 
GET http://localhost:1337/vendors 
